services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - BASE_URL=https://aiostreams.replace.me
      - AIOSTREAMS_AUTH=user:pass
      - SECRET_KEY=
    volumes:
      - ./data:/app/data
    networks:
      - pangolin_frontend
      - aiostreams # Make sure to create this network first in Dockhand-> Networks -> "+ Create"

networks:
  pangolin_frontend:
    external: true
  aiostreams:
    external: true
